name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Install docker-compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Build Docker image
        run: |
          cd ansible-docker/docker
          docker build -t my-nginx-app .

      - name: Run docker-compose
        run: |
          cd ansible-docker
          docker-compose up -d

      - name: Wait for nginx to be available
        run: |
          sleep 5
          curl -v http://localhost:80

      - name: Log docker-compose output
        run: |
          cd ansible-docker
          docker-compose logs
